import CONSTANTS from '../../data/constants.json';
import WEAPONS from '../../data/weapons.json';
import type { AbilityScores } from '../Entity/types';

const {
  WEAPONS: {
    RAPIER,
    GREATAXE,
    HANDAXE,
    DAGGER,
    MACE,
    LIGHT_CROSSBOW,
    SCIMITAR,
    GREATSWORD,
    SHORTSWORD,
    LANCE,
    JAVELIN,
    LONGBOW,
    SHORTBOW,
    QUARTERSTAFF,
  },
  WEAPON_TYPES: {
    SIMPLE,
    MARTIAL,
  },
  DAMAGE_TYPES: {
    ACID,    
    BLUDGEONING,
    COLD,
    FIRE,
    FORCE,
    LIGHTNING,
    NECROTIC,
    PIERCING,
    POISON,
    PSYCHIC,
    RADIANT,
    SLASHING,
    THUNDER,
  },
  ATTACK_TYPES: {
    MELEE,
    RANGED,
  },
} = CONSTANTS;

export default {
  [GREATAXE]: {
    name: "swing greataxe",
    weaponType: MARTIAL,
    attackType: MELEE,
    targetCount: 1,
    damage: 12,
    damageType: SLASHING,
  },
  [HANDAXE]: {
    name: "swing handaxe",
    weaponType: SIMPLE,
    attackType: MELEE,
    targetCount: 1,
    damage: 6,
    damageType: SLASHING,
  },
  [RAPIER]: {
    name: "stab with rapier",
    weaponType: MARTIAL,
    attackType: MELEE,
    targetCount: 1,
    damage: 8,
    damageType: PIERCING,
    finesse: true,
  },
  [DAGGER]: {
    name: "stab with dagger",
    weaponType: SIMPLE,
    attackType: MELEE,
    targetCount: 1,
    damage: 4,
    damageType: PIERCING,
    finesse: true,
  },
  [MACE]: {
    name: "swing mace",
    weaponType: SIMPLE,
    attackType: MELEE,
    targetCount: 1,
    damage: 6,
    damageType: BLUDGEONING,
  },
  [LIGHT_CROSSBOW]: {
    name: "shoot light crossbow",
    weaponType: SIMPLE,
    attackType: RANGED,
    targetCount: 1,
    damage: 8,
    damageType: PIERCING,
  },
  [SCIMITAR]: {
    name: "swing scimitar",
    weaponType: SIMPLE,
    attackType: MELEE,
    targetCount: 1,
    damage: 6,
    damageType: SLASHING,
  },
  [GREATSWORD]: {
    name: "swing greatsword",
    weaponType: MARTIAL,
    attackType: MELEE,
    targetCount: 1,
    damage: 12,
    damageType: SLASHING,
  },
  [SHORTSWORD]: {
    name: "swing shortsword",
    weaponType: SIMPLE,
    attackType: MELEE,
    targetCount: 1,
    damage: 6,
    damageType: PIERCING,
    finesse: true,
  },
  [LANCE]: {
    name: "pierce with lance",
    weaponType: MARTIAL,
    attackType: MELEE,
    targetCount: 1,
    damage: 12,
    damageType: PIERCING,
  },
  [JAVELIN]: {
    name: "throws a javelin",
    weaponType: SIMPLE,
    attackType: RANGED,
    targetCount: 1,
    damage: 6,
    damageType: PIERCING,
  },
  [LONGBOW]: {
    name: "shoot longbow",
    weaponType: MARTIAL,
    attackType: RANGED,
    targetCount: 1,
    damage: 8,
    damageType: PIERCING,
  },
  [SHORTBOW]: {
    name: "shoot shortbow",
    weaponType: SIMPLE,
    attackType: RANGED,
    targetCount: 1,
    damage: 6,
    damageType: PIERCING,
  },
  [QUARTERSTAFF]: {
    name: "swing quarterstaff",
    weaponType: SIMPLE,
    attackType: MELEE,
    targetCount: 1,
    damage: 6,
    damageType: BLUDGEONING,
  },
};

